### ISSUE TITLE
启动http://127.0.0.1:8080/xxl-job-admin/api 调用失败

### ISSUE THREAD

**Issue by andybbc** [YSOcean/xxljobexecutordemo#1]
xxl-job-admin已经启动，但是本项目启动调用admin接口失败了

11:29:52.503 logback [Thread-19] INFO  c.x.r.r.i.r.XxlRpcReferenceBean - >>>>>>>>>>> xxl-job, invoke error, address:http://127.0.0.1:8080/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='36f3114b-605e-422b-8633-9d682b35995f', createMillisTime=1582169392500, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='registry', parameterTypes=[class com.xxl.job.core.biz.model.RegistryParam], parameters=[RegistryParam{registGroup='EXECUTOR', registryKey='executorDemo', registryValue='127.0.0.1:9999'}], version='null'}
11:29:52.503 logback [Thread-19] INFO  c.x.j.c.t.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='executorDemo', registryValue='127.0.0.1:9999'}
com.xxl.rpc.util.XxlRpcException: xxl-rpc remoting request fail, http HttpStatus[302] invalid.
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:161)
	at com.sun.proxy.$Proxy53.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
	at java.lang.Thread.run(Thread.java:748)

**Comment by yanhl0326** [comment]
我现在也遇到这个问题了，请问大佬解决了么？

**Comment by yanhl0326** [comment]
我现在也遇到这个问题了，请问大佬解决了么？
[Thread-3] c.x.r.r.i.r.XxlRpcReferenceBean [XxlRpcReferenceBean.java : 225] >>>>>>>>>>> xxl-rpc, invoke error, address:http://10.78.223.233:8888/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='2872da78-c073-4612-aa63-087ba2813cd8', createMillisTime=1603869308924, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='callback', parameterTypes=[interface java.util.List], parameters=[[HandleCallbackParam{logId=816448, logDateTim=1603800000070, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=816440, logDateTim=1603800000059, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=816478, logDateTim=1603800000396, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=816468, logDateTim=1603800000191, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=816456, logDateTim=1603800000075, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=816466, logDateTim=1603800000186, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=816455, logDateTim=1603800000079, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=816462, logDateTim=1603800000085, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=816463, logDateTim=1603800000164, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=816467, logDateTim=1603800000191, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=816464, logDateTim=1603800000168, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=816471, logDateTim=1603800000389, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=816450, logDateTim=1603800000073, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=816446, logDateTim=1603800000069, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=816475, logDateTim=1603800000394, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=816459, logDateTim=1603800000079, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=816441, logDateTim=1603800000064, executeResult=ReturnT [code=200, msg=null, content=null]}]], version='null'}
